saveExact: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vitest: 4.1.10
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  unrs-resolver: true
