name: CI

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - run: npm run lint:ci
      - run: npm run type-check
      - run: npm run build
      - run: npm run test:ci
