name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next

concurrency:
  group: Release
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          registry-url: https://registry.npmjs.org

      - run: vp check
      - run: vp test
      - run: vp pack

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: vp exec semantic-release
